<?php
namespace Albatool\ProductAttribute\Model\Config\Source;

use Magento\Eav\Model\Entity\Attribute\Source\AbstractSource;

class ProducttypeOptions extends AbstractSource
{
    
    public function getAllOptions()
    {
        if (null === $this->_options) {
            
                $this->_options=[
                                ['label' => __('Cleanser'), 'value' => '1'],
                                ['label' => __('Make Up Remover'), 'value' => '2'],
                                ['label' => __('Serum cure'), 'value' => '3'],
                                ['label' => __('Day cream'), 'value' => '4'],
                                ['label' => __('Night cream'), 'value' => '5'],
                                ['label' => __('Anti-aging cream'), 'value' => '6'],
                                ['label' => __('Bb-cream'), 'value' => '7'],
                                ['label' => __('Men face care'), 'value' => '8'],
                                ['label' => __('Scrub Mask'), 'value' => '9'],
                                ['label' => __('Eye-contour'), 'value' => '10'],
                                ['label' => __('Lips care'), 'value' => '11'],
                                ['label' => __('Accessories'), 'value' => '12'],
                                ['label' => __('Kit'), 'value' => '13'],
                                ['label' => __('Nettoyant'), 'value' => '14'],
                                ['label' => __('Démaquillant'), 'value' => '15'],
                                ['label' => __('Sérum et cure'), 'value' => '16'],
                                ['label' => __('Crème de jour'), 'value' => '17'],
                                ['label' => __('Crème de nuit'), 'value' => '18'],
                                ['label' => __('Soin anti-âge'), 'value' => '19'],
                                ['label' => __('BB crème'), 'value' => '20'],
                                ['label' => __('Hydratant et nettoyant homme'), 'value' => '21'],
                                ['label' => __('Gommage et masque'), 'value' => '22'],
                                ['label' => __('Contour regard'), 'value' => '23'],
                                ['label' => __('Soin des lèvres'), 'value' => '24'],
                                ['label' => __('Avec FPS?'), 'value' => '25'],
                                ['label' => __('Composition et coffret'), 'value' => '26'],
                                ['label' => __('Base'), 'value' => '27'],
                                ['label' => __('Blush'), 'value' => '28'],
                                ['label' => __('Lip contour'), 'value' => '29'],
                                ['label' => __('Eye pencil'), 'value' => '30'],
                                ['label' => __('Nail polish remover'), 'value' => '31'],
                                ['label' => __('Eyeliner'), 'value' => '32'],
                                ['label' => __('Eyeshadow'), 'value' => '33'],
                                ['label' => __('Gloss'), 'value' => '34'],
                                ['label' => __('Mascara'), 'value' => '35'],
                                ['label' => __('Make-Up palette'), 'value' => '36'],
                                ['label' => __('Powder'), 'value' => '37'],
                                ['label' => __('Lipstick'), 'value' => '38'],
                                ['label' => __('Hand & Nail Care'), 'value' => '39'],
                                ['label' => __('Eyebrows'), 'value' => '40'],
                                ['label' => __('Nail polish'), 'value' => '41'],
                                ['label' => __('Bronzer'), 'value' => '42'],
                                ['label' => __('Foundation'), 'value' => '43'],
                                ['label' => __('Concealer'), 'value' => '44'],
                                ['label' => __('Highlighter'), 'value' => '45'],
                                ['label' => __('Contour des lèvres'), 'value' => '46'],
                                ['label' => __('Crayon yeux'), 'value' => '47'],
                                ['label' => __('Dissolvant'), 'value' => '48'],
                                ['label' => __('Liner'), 'value' => '49'],
                                ['label' => __('Fard à paupières'), 'value' => '50'],
                                ['label' => __('Palette de maquillage'), 'value' => '51'],
                                ['label' => __('Poudre'), 'value' => '52'],
                                ['label' => __('Rouge à lèvres'), 'value' => '53'],
                                ['label' => __('Soin des mains et des ongles'), 'value' => '54'],
                                ['label' => __('Mascara & Crayon Sourcils'), 'value' => '55'],
                                ['label' => __('Vernis à ongles'), 'value' => '56'],
                                ['label' => __('Poudre de soleil'), 'value' => '57'],
                                ['label' => __('Fond de teint'), 'value' => '58'],
                                ['label' => __('Correcteur et anti-cernes'), 'value' => '59'],
                                ['label' => __('Enlumineur - Highlighter'), 'value' => '60'],
                                ['label' => __('Hand Care'), 'value' => '61'],
                                ['label' => __('Feet care'), 'value' => '62'],
                                ['label' => __('Firming & Slimming Care'), 'value' => '63'],
                                ['label' => __('Monoi'), 'value' => '64'],
                                ['label' => __('Scrub'), 'value' => '65'],
                                ['label' => __('Food supplement'), 'value' => '66'],
                                ['label' => __('Soin des pieds'), 'value' => '67'],
                                ['label' => __('Soin Minceur et Fermeté'), 'value' => '68'],
                                ['label' => __('Monoï'), 'value' => '69'],
                                ['label' => __('Gommage'), 'value' => '70'],
                                ['label' => __('Complément alimentaire'), 'value' => '71'],
                                ['label' => __('Accessoires'), 'value' => '72'],
                                ['label' => __('Sun protection'), 'value' => '73'],
                                ['label' => __('After sun'), 'value' => '74'],
                                ['label' => __('Self Tanner'), 'value' => '75'],
                                ['label' => __('Moisturizer'), 'value' => '76'],
                                ['label' => __('Protection solaire'), 'value' => '77'],
                                ['label' => __('Après-solaire'), 'value' => '78'],
                                ['label' => __('Autobronzant'), 'value' => '79'],
                                ['label' => __('Soin hydratant'), 'value' => '80'],
                                ['label' => __('Shampoo'), 'value' => '81'],
                                ['label' => __('Treatment'), 'value' => '82'],
                                ['label' => __('Hair Mask'), 'value' => '83'],
                                ['label' => __('Conditioner'), 'value' => '84'],
                                ['label' => __('Serum No Rinse Care'), 'value' => '85'],
                                ['label' => __('Before Shampoo'), 'value' => '86'],
                                ['label' => __('Rinsing vinegar'), 'value' => '87'],
                                ['label' => __('Shampooing'), 'value' => '88'],
                                ['label' => __('Traitement'), 'value' => '89'],
                                ['label' => __('Masque cheveux'), 'value' => '90'],
                                ['label' => __('Après-shampooing'), 'value' => '91'],
                                ['label' => __('Sérum et Soin sans rinçage'), 'value' => '92'],
                                ['label' => __('Pré-Shampooing'), 'value' => '93'],
                                ['label' => __('Vinaigre de rinçage'), 'value' => '94'],
                                ['label' => __('FRESH_WATER'), 'value' => '95'],
                                ['label' => __('EAU_TOILETTE'), 'value' => '96'],
                                ['label' => __('EAU_PARFUM'), 'value' => '97'],
                                ['label' => __('Hair & Body Mist'), 'value' => '98'],
                                ['label' => __('Eau fraiche'), 'value' => '99'],
                                ['label' => __('Eau de toilette'), 'value' => '100'],
                                ['label' => __('Eau de parfum'), 'value' => '101'],
                                ['label' => __('Brume corps et cheveux'), 'value' => '102'],
                                ['label' => __('Shower gel'), 'value' => '103'],
                                ['label' => __('Exfoliating shower gel'), 'value' => '104'],
                                ['label' => __('Shower oil'), 'value' => '105'],
                                ['label' => __('Deodorant'), 'value' => '106'],
                                ['label' => __('Liquid hand soap'), 'value' => '107'],
                                ['label' => __('Bath Bomb'), 'value' => '108'],
                                ['label' => __('Soap'), 'value' => '109'],
                                ['label' => __('Gel douche'), 'value' => '110'],
                                ['label' => __('Gel douche gommant'), 'value' => '111'],
                                ['label' => __('Huile de douche'), 'value' => '112'],
                                ['label' => __('Déodorant'), 'value' => '113'],
                                ['label' => __('Gel lavant mains'), 'value' => '114'],
                                ['label' => __('Bombe de bain'), 'value' => '115'],
                                ['label' => __('Savon'), 'value' => '116'],
                                ['label' => __('Foot care'), 'value' => '117'],
                                ['label' => __('Mask'), 'value' => '118'],
                                ['label' => __('Masque'), 'value' => '119'],
                                ['label' => __('Self Tanner Summer Glow'), 'value' => '120'],
                                ['label' => __('Autobronzant et ensoleillant'), 'value' => '121'],
                                ['label' => __('Vinegar'), 'value' => '122'],
                                ['label' => __('Vinaigre'), 'value' => '123']
                            ];
        }

        return $this->_options;
    }
}