<?php
/**
 * @category   Albatool
 * @package    Albatool_CityDropList
 * @author     venkateshwarlu.neredu@ambab.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Albatool\CityDropList\Controller\Adminhtml\Items;

class Index extends \Albatool\CityDropList\Controller\Adminhtml\Items
{
    /**
     * Items list.
     *
     * @return \Magento\Backend\Model\View\Result\Page
     */
    public function execute()
    {
        /** @var \Magento\Backend\Model\View\Result\Page $resultPage */
        $resultPage = $this->resultPageFactory->create();
        $resultPage->setActiveMenu('Albatool_CityDropList::test');
        $resultPage->getConfig()->getTitle()->prepend(__('City Items'));
        $resultPage->addBreadcrumb(__('City'), __('City'));
        $resultPage->addBreadcrumb(__('Items'), __('Items'));
        return $resultPage;
    }
}