<?php
namespace Albatool\StoreLocator\Setup;

use Magento\Framework\Setup\UpgradeDataInterface;
use Magento\Framework\Setup\ModuleDataSetupInterface;
use Magento\Framework\Setup\ModuleContextInterface;
use Magento\InventoryApi\Api\Data\SourceInterface;

class UpgradeData implements UpgradeDataInterface
{
    /**
     * @var ResourceConnection
     */
    private $resource;

    /**
     * UpgradeData constructor.
     * @param ResourceConnection $resource
     */
    public function __construct(
        \Magento\Framework\App\ResourceConnection $resource
    ) {
        $this->resource = $resource;
    }

    /**
     * @param ModuleDataSetupInterface $setup
     * @param ModuleContextInterface $context
     */
    public function upgrade(ModuleDataSetupInterface $setup, ModuleContextInterface $context) {
        if (version_compare($context->getVersion(), '1.2.2', '<')) {
            $connection = $this->resource->getConnection();

            $storeData = [
                [
                    "source_code" => '1',
                    "name" => 'Othaim Mall, Riyadh',
                    "enabled" => 1,
                    "latitude" => 24.750359,
                    "longitude" => 46.822851,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Othaim Mall, Ground Floor - Gate 2',
                    "postcode" => '12839',
                    "phone" => '011-2338233',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '2',
                    "name" => 'Andalus Mall',
                    "enabled" => 1,
                    "latitude" => 21.506912,
                    "longitude" => 39.218254,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Andalus Mall, Ground Floor - Gate 2',
                    "postcode" => '22245',
                    "phone" => '012-6303670',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '4',
                    "name" => 'Granada Mall',
                    "enabled" => 1,
                    "latitude" => 24.78193,
                    "longitude" => 46.730548,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Granada Mall, 2nd floor',
                    "postcode" => '22245',
                    "phone" => '011-2535388',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '5',
                    "name" => 'Aziz Mall',
                    "enabled" => 1,
                    "latitude" => 21.576487,
                    "longitude" => 39.197083,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Aziz Mall, 2nd floor - cross Banda',
                    "postcode" => '23447',
                    "phone" => '012-6161850',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '7',
                    "name" => 'Hayat Mall',
                    "enabled" => 1,
                    "latitude" => 24.743468,
                    "longitude" => 46.68091,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Hayat Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '011-2057207',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '10',
                    "name" => 'Red Sea Mall',
                    "enabled" => 1,
                    "latitude" => 21.627606,
                    "longitude" => 39.110861,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Red Sea Mall, Ground Floor - cross Danube',
                    "postcode" => '23447',
                    "phone" => '012-2150147',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '11',
                    "name" => 'jamea Plaza',
                    "enabled" => 1,
                    "latitude" => 21.482643,
                    "longitude" => 39.241761,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'jamea Plaza, 2nd floor',
                    "postcode" => '23447',
                    "phone" => '012-6870653',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '12',
                    "name" => 'Obaikan Mall',
                    "enabled" => 1,
                    "latitude" => 21.287165,
                    "longitude" => 40.418561,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Taif',
                    "street" => 'Obaikan Mall, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '012-7331104',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '13',
                    "name" => 'Mall of Dhahran',
                    "enabled" => 1,
                    "latitude" => 26.305765,
                    "longitude" => 50.169341,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Dahran',
                    "street" => 'Dhahran Mall, Ground Floor - Gate 4',
                    "postcode" => '23447',
                    "phone" => '013-8681388',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '14',
                    "name" => 'Noor Mall',
                    "enabled" => 1,
                    "latitude" => 24.496159,
                    "longitude" => 39.595605,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Medina Region',
                    "city" => 'Al Madeena',
                    "street" => 'Noor Mall, 2nd floor - cross Banda',
                    "postcode" => '23447',
                    "phone" => '014-8494315',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '15',
                    "name" => 'Nakheel Mall',
                    "enabled" => 1,
                    "latitude" => 26.368108,
                    "longitude" => 43.961779,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qassim',
                    "street" => 'Nakheel Mall, Ground Floor - Gate 4',
                    "postcode" => '23447',
                    "phone" => '016-3836682',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '16',
                    "name" => 'Rashed Mall',
                    "enabled" => 1,
                    "latitude" => 24.487792,
                    "longitude" => 39.648982,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Madina Region',
                    "city" => 'Al Madeena',
                    "street" => 'Rashed Mall, 2nd Floor',
                    "postcode" => '23447',
                    "phone" => '014-8358470',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '17',
                    "name" => 'Mall of Arabia',
                    "enabled" => 1,
                    "latitude" => 21.632653,
                    "longitude" => 39.156158,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Mall of Arabia, Ground Floor - Gate 5',
                    "postcode" => '23447',
                    "phone" => '012-6122895',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '18',
                    "name" => 'Roshan Mall',
                    "enabled" => 1,
                    "latitude" => 21.665653,
                    "longitude" => 39.109478,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Roshan Mall, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '012-2368188',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '19',
                    "name" => 'Tabuk Centre',
                    "enabled" => 1,
                    "latitude" => 28.394232,
                    "longitude" => 36.548716,
                    "country_id" => 'SA',
                    "region_id" => 1108,
                    "region" => 'Tabuk Region',
                    "city" => 'Tabuk',
                    "street" => 'Tabuk Centre, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '014-4232962',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '20',
                    "name" => 'Dareen Mall',
                    "enabled" => 1,
                    "latitude" => 26.461231,
                    "longitude" => 50.064968,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Dammam',
                    "street" => 'Dareen Mall, 2nd Floor',
                    "postcode" => '23447',
                    "phone" => '013-8309156',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '21',
                    "name" => 'Amwaj Mall',
                    "enabled" => 1,
                    "latitude" => 26.310019,
                    "longitude" => 50.171352,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Dahran',
                    "street" => 'Amwaj Mall, Ground Floor - Gate 7',
                    "postcode" => '23447',
                    "phone" => '013-8686215',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '22',
                    "name" => 'Othaim Mall, Al Hassa',
                    "enabled" => 1,
                    "latitude" => 25.400317,
                    "longitude" => 49.578334,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Hassa',
                    "street" => 'Hassa Mall, Ground Floor - Gate 4',
                    "postcode" => '23447',
                    "phone" => '013-5320290',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '23',
                    "name" => 'Unaiza Plaza',
                    "enabled" => 1,
                    "latitude" => 26.092884,
                    "longitude" => 43.973786,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qasiem',
                    "street" => 'Unaiza Plaza, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "phone" => '016-3631849',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '24',
                    "name" => 'Buraida Plaza',
                    "enabled" => 1,
                    "latitude" => 26.373916,
                    "longitude" => 43.93652,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qasiem',
                    "street" => 'Buraida Plaza, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '016-3834792',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '25',
                    "name" => 'Rabwa Mall',
                    "enabled" => 1,
                    "latitude" => 24.684536,
                    "longitude" => 46.774694,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Rabwa Mall, Ground Floor - Gate 3',
                    "postcode" => '23447',
                    "phone" => '011-4456654',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '27',
                    "name" => 'Aseer Mall',
                    "enabled" => 1,
                    "latitude" => 18.239801,
                    "longitude" => 42.604341,
                    "country_id" => 'SA',
                    "region_id" => 1104,
                    "region" => 'Asir Region',
                    "city" => 'Abha',
                    "street" => 'Aseer Mall, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "phone" => '017-2250770',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '28',
                    "name" => 'Kadi Mall',
                    "enabled" => 1,
                    "latitude" => 16.909168,
                    "longitude" => 42.545641,
                    "country_id" => 'SA',
                    "region_id" => 1105,
                    "region" => 'Jizan Region',
                    "city" => 'Jizan',
                    "street" => 'Kadi Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '017-3235481',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '29',
                    "name" => 'Haifa Mall',
                    "enabled" => 1,
                    "latitude" => 21.527257,
                    "longitude" => 39.177902,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Haifa Mall, Ground Floor - Gate 3',
                    "postcode" => '23447',
                    "phone" => '012-6610387',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '30',
                    "name" => 'Makkah Mall',
                    "enabled" => 1,
                    "latitude" => 21.391587,
                    "longitude" => 39.884622,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Makkah',
                    "street" => 'Makkah Mall, Ground Floor - Cross Banda',
                    "postcode" => '23447',
                    "phone" => '012-5531925',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '31',
                    "name" => 'Othaim Mall, Dammam',
                    "enabled" => 1,
                    "latitude" => 26.400199,
                    "longitude" => 50.116952,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Dammam',
                    "street" => 'Othaim Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '013-8318258',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '32',
                    "name" => 'Yanbu Mall',
                    "enabled" => 1,
                    "latitude" => 24.089139,
                    "longitude" => 38.048403,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Medina Region',
                    "city" => 'Yanbu',
                    "street" => 'Yanbu Mall, Groun Floor',
                    "postcode" => '23447',
                    "phone" => '014-3908967',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '35',
                    "name" => 'Garden Mall',
                    "enabled" => 1,
                    "latitude" => 27.554638,
                    "longitude" => 41.681593,
                    "country_id" => 'SA',
                    "region_id" => 1110,
                    "region" => 'Najran Region',
                    "city" => 'Hail',
                    "street" => 'Garden Mall, 2nd Floor - Gate 5',
                    "postcode" => '23447',
                    "phone" => '016-5437692',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '36',
                    "name" => 'Salam Riyadh',
                    "enabled" => 1,
                    "latitude" => 24.558526,
                    "longitude" => 46.637741,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Salam Mall, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '011-8104526',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '38',
                    "name" => 'Hijaz Makkah',
                    "enabled" => 1,
                    "latitude" => 21.423619,
                    "longitude" => 39.781904,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Makkah',
                    "street" => 'Hijaz Plaza, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '012-5457467',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '39',
                    "name" => 'Rashed Mall',
                    "enabled" => 1,
                    "latitude" => 16.902697,
                    "longitude" => 42.553585,
                    "country_id" => 'SA',
                    "region_id" => 1105,
                    "region" => 'Jizan Region',
                    "city" => 'Jizan',
                    "street" => 'Rashed Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '017-3229524',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '41',
                    "name" => 'Aliay Al Madeena Mall',
                    "enabled" => 1,
                    "latitude" => 24.413623,
                    "longitude" => 39.618961,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Medina Region',
                    "city" => 'Al Madeena',
                    "street" => 'Aliay Al.Madeena Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '014-8488791',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '42',
                    "name" => 'Sahara Mall',
                    "enabled" => 1,
                    "latitude" => 25.866817,
                    "longitude" => 43.506404,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qasiem',
                    "street" => 'Sahara Mall, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "phone" => '016-3331464',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '43',
                    "name" => 'Dana Mall',
                    "enabled" => 1,
                    "latitude" => 24.032944,
                    "longitude" => 38.192641,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Medina Region',
                    "city" => 'Yanbu',
                    "street" => 'Dana Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '014-3921110',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '44',
                    "name" => 'Manar Mall',
                    "enabled" => 1,
                    "latitude" => 24.459996,
                    "longitude" => 39.58473,
                    "country_id" => 'SA',
                    "region_id" => 1106,
                    "region" => 'Medina Region',
                    "city" => 'Al Madeena',
                    "street" => 'Manar Mall, 2nd Floor',
                    "postcode" => '23447',
                    "phone" => '014-8220686',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '45',
                    "name" => 'Tala Mall',
                    "enabled" => 1,
                    "latitude" => 24.771348,
                    "longitude" => 46.669219,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Tala Mall, Ground Floor - Cross Banda',
                    "postcode" => '23447',
                    "phone" => '011-4154937',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '46',
                    "name" => 'Nakheel Mall',
                    "enabled" => 1,
                    "latitude" => 24.767947,
                    "longitude" => 46.71573,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Nakheel Mall, Ground Floor - Cross Virgin Mega store',
                    "postcode" => '23447',
                    "phone" => '011-4158624',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '48',
                    "name" => 'Al Jouf Plaza',
                    "enabled" => 1,
                    "latitude" => 29.954141,
                    "longitude" => 40.191683,
                    "country_id" => 'SA',
                    "region_id" => 1111,
                    "region" => 'Al-Jawf Region',
                    "city" => 'Jouf',
                    "street" => 'Jouf Center, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 1,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '50',
                    "name" => 'Sarwat Mall',
                    "enabled" => 1,
                    "latitude" => 24.543247,
                    "longitude" => 44.439484,
                    "country_id" => 'SA',
                    "region_id" => 1112,
                    "region" => 'Al-Bahah Region',
                    "city" => 'Sabia',
                    "street" => 'Sarwat Mall, Ground Floor - Cross Othaim Supermarket',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '52',
                    "name" => 'Jouri Mall',
                    "enabled" => 1,
                    "latitude" => 21.277179,
                    "longitude" => 40.444863,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Taif',
                    "street" => 'Jouri Mall, Ground Floor - Gate 4',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '53',
                    "name" => 'Al Waha Mall',
                    "enabled" => 1,
                    "latitude" => 25.896596,
                    "longitude" => 43.471565,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qasiem',
                    "street" => 'Al Waha Mall, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '54',
                    "name" => 'Al Makan Mall',
                    "enabled" => 1,
                    "latitude" => 28.358465,
                    "longitude" => 45.962377,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Hafr Al.Batin',
                    "street" => 'Al Makan Mall, Ground Floor',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '55',
                    "name" => 'Othaim Mall-Unaizah',
                    "enabled" => 1,
                    "latitude" => 26.107402,
                    "longitude" => 43.994582,
                    "country_id" => 'SA',
                    "region_id" => 1107,
                    "region" => 'Qassim Region',
                    "city" => 'Qasiem',
                    "street" => 'Othaim Mall, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '56',
                    "name" => 'Othaim Mall-Arar',
                    "enabled" => 1,
                    "latitude" => 30.954721,
                    "longitude" => 41.010493,
                    "country_id" => 'SA',
                    "region_id" => 1113,
                    "region" => 'Northern Borders Region',
                    "city" => 'Arar',
                    "street" => 'Othaim Mall, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '57',
                    "name" => 'Grand Mall, Hail',
                    "enabled" => 1,
                    "latitude" => 27.473638,
                    "longitude" => 41.677398,
                    "country_id" => 'SA',
                    "region_id" => 1108,
                    "region" => 'Tabuk Region',
                    "city" => 'Hail',
                    "street" => 'Grand Mall, Ground Floor - Gate 2',
                    "postcode" => '23447',
                    "phone" => '014-6253686',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '58',
                    "name" => 'Khamis Avenue',
                    "enabled" => 1,
                    "latitude" => 18.246861,
                    "longitude" => 42.765318,
                    "country_id" => 'SA',
                    "region_id" => 1104,
                    "region" => 'Asir Region',
                    "city" => 'Khamis Musheet',
                    "street" => 'Khamis Avenue, Ground Floor - Gate 4',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '59',
                    "name" => 'Faisaliah Center, Riyadh',
                    "enabled" => 1,
                    "latitude" => 24.6905765,
                    "longitude" => 46.6829083,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Faisaliah Center, 3rd Floor',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '60',
                    "name" => 'Rashed Abha',
                    "enabled" => 1,
                    "latitude" => 18.237577,
                    "longitude" => 42.580554,
                    "country_id" => 'SA',
                    "region_id" => 1104,
                    "region" => 'Asir Region',
                    "city" => 'Abha',
                    "street" => 'Rashed Abha, Ground Floor - Gate 6',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '61',
                    "name" => 'Yasmeen Mall',
                    "enabled" => 1,
                    "latitude" => 21.593228,
                    "longitude" => 39.228605,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Yasmeen Mall, Ground Floor - Gate 5',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '67',
                    "name" => 'Diyafa Mall',
                    "enabled" => 1,
                    "latitude" => 21.441647,
                    "longitude" => 39.800622,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Makkah',
                    "street" => 'Diyafa Mall, 1st floor - Gate 7 - Cross Starbuks',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '66',
                    "name" => 'Nakheel Dammam',
                    "enabled" => 1,
                    "latitude" => 26.391427,
                    "longitude" => 50.037448,
                    "country_id" => 'SA',
                    "region_id" => 1103,
                    "region" => 'Eastern Region',
                    "city" => 'Dammam',
                    "street" => 'Nakheel Dammam, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '64',
                    "name" => 'Salam Jeddah',
                    "enabled" => 1,
                    "latitude" => 21.507974,
                    "longitude" => 39.223332,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Salam Jeddah, 2nd Floor - Gate 3',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '62',
                    "name" => 'Tabuk Park',
                    "enabled" => 1,
                    "latitude" => 28.429487,
                    "longitude" => 36.572782,
                    "country_id" => 'SA',
                    "region_id" => 1108,
                    "region" => 'Tabuk Region',
                    "city" => 'Tabuk',
                    "street" => 'Tabuk Park, Ground Floor',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '70',
                    "name" => 'Riyadh Gallery',
                    "enabled" => 1,
                    "latitude" => 24.7437835727511,
                    "longitude" => 46.658095013259,
                    "country_id" => 'SA',
                    "region_id" => 1102,
                    "region" => 'Riyadh Region',
                    "city" => 'Riyadh',
                    "street" => 'Riyadh Gallery, 1st floor - gate 2',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '75',
                    "name" => 'Rashed Kiosk, Abha',
                    "enabled" => 1,
                    "latitude" => 18.237577,
                    "longitude" => 42.580554,
                    "country_id" => 'SA',
                    "region_id" => 1104,
                    "region" => 'Asir Region',
                    "city" => 'Abha',
                    "street" => 'Rashed Kiosk, Abha, 1st floor - gate 2',
                    "postcode" => '23447',
                    "phone" => '017-2273949',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '73',
                    "name" => 'Jeddah Park',
                    "enabled" => 1,
                    "latitude" => 21.556392,
                    "longitude" => 39.185802,
                    "country_id" => 'SA',
                    "region_id" => 1101,
                    "region" => 'Mecca Region',
                    "city" => 'Jeddah',
                    "street" => 'Jeddah Park, Ground floor - gate 2',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ],

                [
                    "source_code" => '71',
                    "name" => 'Mujan Mall, Abha',
                    "enabled" => 1,
                    "latitude" => 18.285217,
                    "longitude" => 42.739994,
                    "country_id" => 'SA',
                    "region_id" => 1104,
                    "region" => 'Asir Region',
                    "city" => 'Khamis Musheet',
                    "street" => 'Mojan Park, Ground Floor - Gate 1',
                    "postcode" => '23447',
                    "is_pickup_location_active" => 0,
                    "monday_field" => '10:00,21:30',
                    "tuesday_field" => '10:00,21:30',
                    "wednesday_field" => '10:00,21:30',
                    "thursday_field" => '10:00,21:30',
                    "friday_field" => '10:00,21:30',
                    "saturday_field" => '10:00,21:30',
                    "sunday_field" => '10:00,21:30'
                ]

            ];

            for($i = 0; $i < count($storeData); $i++) {
                $connection->insert($this->resource->getTableName('inventory_source'), $storeData[$i]);
            }

        }
    }

}
