<?php
/**
 * @category   Albatool
 * @package    Albatool_CityDropList
 * @author     venkateshwarlu.neredu@ambab.com
 * @copyright  This file was generated by using Module Creator(http://code.vky.co.in/magento-2-module-creator/) provided by VKY <viky.031290@gmail.com>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

namespace Albatool\CityDropList\Model\ResourceModel\CityDropList;
 
class Collection extends \Magento\Framework\Model\ResourceModel\Db\Collection\AbstractCollection
{
    protected $_idFieldName = 'citydroplist_id';
    /**
     * Define model & resource model
     */
    protected function _construct()
    {
        $this->_init(
            'Albatool\CityDropList\Model\CityDropList',
            'Albatool\CityDropList\Model\ResourceModel\CityDropList'
        );
    }
}